### ISSUE TITLE
Support fastboot flash paralloid

### ISSUE THREAD

**Issue by phhusson** [Paralloid/Paralloid#2]
`fastboot flash paralloid rootfs.img` should upgrade paralloid.

This is not trivial, since paralloid is currently running. The trick is to remove `paralloid_old`, create a new `paralloid_tmp` partition, flash to it, then rename `paralloid` to `paralloid_old` and `paralloid_tmp` to `paralloid`. This way, the sectors currently in use remain allocated until next flash.

See https://github.com/phhusson/device_phh_treble/blob/android-11.0/cmds/lptools.cc#L181 on how to rename dynamic partitions

**Comment by PeterCxy** [comment]
this would not work on non-dynamic SaR though. Maybe we should consider (somehow) running the entire Paralloid rootfs in RAM instead just like recovery? This way 1) it would work on non-dynamic; 2) we don't need to pull in logical partitions dependencies (for this feature, that is)/

**Comment by 00p513-dev** [comment]
BTW this is what ABM is doing, but it will need patching kernels and building per device. What if OEM doesn't release kernel source?

**Comment by 00p513-dev** [comment]
Also it would break recovery

**Comment by PeterCxy** [comment]
@00p513-dev what do you mean? Self-flashing or running from memory? I don't see why either of those need kernel patches or would break recovery?

**Comment by 00p513-dev** [comment]
I am guessing you meant running as a ramdisk? That would be in the boot image, which also needs a kernel patch to actually load the initramfs, since it is only used for recovery now.

**Comment by PeterCxy** [comment]
@00p513-dev yes I meant a ramdisk, but not in the sense of the initial ramdisk. I mean something like dd-ing the entire rootfs to an image in /tmp and pivot_root into it to free up the original block device.

**Comment by 00p513-dev** [comment]
> @00p513-dev yes I meant a ramdisk, but not in the sense of the initial ramdisk. I mean something like dd-ing the entire rootfs to an image in /tmp and pivot_root into it to free up the original block device.

ahh makes sense thx for clarifying

**Comment by PeterCxy** [comment]
With #10, we should be able to flash the system block device without worrying about it being in use.

**Comment by allmypi51** [comment]
So my phone was hacked and I had or have 2 systems on my phone the hack
used part of the boot from berry boot and it works it's set on or it uses
the VM set up avel.in android 10 looking at your code it could be done that
way as well
